/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bloglist: typeof import('./src/components/Bloglist.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTag: typeof import('element-plus/es')['ElTag']
    Logo: typeof import('./src/components/logo.vue')['default']
    Main_container: typeof import('./src/components/main_container.vue')['default']
    Main_content_left: typeof import('./src/components/main_content_left.vue')['default']
    MainContent: typeof import('./src/components/Main-Content.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PoliceFilingBadge: typeof import('./src/components/PoliceFilingBadge.vue')['default']
    Resume_Detail: typeof import('./src/components/Resume_Detail.vue')['default']
    Resume_List: typeof import('./src/components/Resume_List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaveSeparator: typeof import('./src/components/WaveSeparator.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
